// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGLv_W4WtieDr46D0T97ujCC_6-m1UuEA',
    appId: '1:517759282177:web:4e30de4a796da557df2400',
    messagingSenderId: '517759282177',
    projectId: 'crafty-bay-5bf1d',
    authDomain: 'crafty-bay-5bf1d.firebaseapp.com',
    storageBucket: 'crafty-bay-5bf1d.firebasestorage.app',
    measurementId: 'G-Q4JZLFBPM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1MOZMmOw5e6BxtLk-2mhQdWC83s_8MYo',
    appId: '1:517759282177:android:b1eb08049be612a6df2400',
    messagingSenderId: '517759282177',
    projectId: 'crafty-bay-5bf1d',
    storageBucket: 'crafty-bay-5bf1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX0FaJKQfT8HFgstitowb58FNHSu6hMVM',
    appId: '1:517759282177:ios:496a5cc28d15a86fdf2400',
    messagingSenderId: '517759282177',
    projectId: 'crafty-bay-5bf1d',
    storageBucket: 'crafty-bay-5bf1d.firebasestorage.app',
    iosBundleId: 'com.example.craftybay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGLv_W4WtieDr46D0T97ujCC_6-m1UuEA',
    appId: '1:517759282177:web:e39676255f453be7df2400',
    messagingSenderId: '517759282177',
    projectId: 'crafty-bay-5bf1d',
    authDomain: 'crafty-bay-5bf1d.firebaseapp.com',
    storageBucket: 'crafty-bay-5bf1d.firebasestorage.app',
    measurementId: 'G-YWX3PGKFJS',
  );
}
